#!/usr/bin/env python3
"""Rasterise profile/*.svg into the retro-futurist PNGs the README embeds.

The SVG generated by generate_profile_cards.py is the clean vector source:
layout, type and the deliberate dither graphics. This script gives it the
screen it is pretending to be photographed off.

    python3 tools/render_cards.py [name ...]

Pipeline, in order (order matters -- bloom before scanlines so the glow gets
cut by them, quantisation last so every earlier stage lands on the palette):

  1. rasterise at 2x through headless Chrome
  2. phosphor bloom     bright pixels blurred and screened back over the frame
  3. RGB split          red and blue shifted a sub-pixel apart
  4. scanlines          every other 2x row darkened, so 1 dark line per CSS px
  5. grain              per-pixel gaussian noise
  6. Bayer 8x8 dither   quantised to the palette; tones between palette entries
                        become dot patterns rather than new colours

Output stays at 2x and is embedded at width=880, so the dither reads as fine
texture on a normal display and stays crisp on a retina one.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import tempfile
import zlib

import numpy as np
from PIL import Image, ImageFilter

SCALE = 2
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROFILE = os.path.join(ROOT, "profile")

# The card palette, plus the two lifted steps type is allowed to use. Ordered
# dithering blends between these; nothing outside the list survives.
PALETTE = [
    (0x0A, 0x0A, 0x0A),
    (0x0F, 0x0F, 0x0F),
    (0x12, 0x12, 0x12),
    (0x1E, 0x1E, 0x1E),
    (0x33, 0x33, 0x33),
    (0x58, 0x58, 0x58),
    (0x8B, 0x8B, 0x8B),
    (0xB4, 0xB4, 0xB4),
    (0xE8, 0xE8, 0xE8),
    (0x1B, 0x3F, 0x8F),
    (0x25, 0x63, 0xEB),
    (0x3B, 0x82, 0xF6),
    (0x8A, 0xB4, 0xFA),
]

BLOOM_RADIUS = 6
BLOOM_THRESHOLD = 96
BLOOM_STRENGTH = 0.42
SCANLINE_DEPTH = 0.13
SCANLINE_PERIOD = 2      # CSS pixels per light/dark pair
RGB_SPLIT_MIX = 0.45     # full channel displacement fringes type badly
GRAIN_SIGMA = 2.2      # visible grain, but random noise is what costs PNG bytes
DITHER_STRENGTH = 17.0


def chrome() -> str:
    for name in ("google-chrome", "chromium", "chromium-browser",
                 "google-chrome-stable"):
        found = shutil.which(name)
        if found:
            return found
    raise SystemExit("no chrome/chromium on PATH; cannot rasterise")


def svg_size(path: str) -> tuple[int, int]:
    with open(path, encoding="utf-8") as fh:
        head = fh.read(400)
    w = int(float(head.split('width="', 1)[1].split('"', 1)[0]))
    h = int(float(head.split('height="', 1)[1].split('"', 1)[0]))
    return w, h


def rasterise(svg_path: str, w: int, h: int) -> Image.Image:
    """Screenshot the SVG at SCALE via headless Chrome."""
    with tempfile.TemporaryDirectory() as tmp:
        page = os.path.join(tmp, "page.html")
        shot = os.path.join(tmp, "shot.png")
        with open(page, "w", encoding="utf-8") as fh:
            fh.write(
                f'<html><body style="margin:0;padding:0;background:#0d1117">'
                f'<img src="file://{svg_path}" width="{w}" height="{h}" '
                f'style="display:block">')
        subprocess.run(
            [chrome(), "--headless=new", "--disable-gpu", "--no-sandbox",
             "--hide-scrollbars", "--default-background-color=00000000",
             f"--force-device-scale-factor={SCALE}",
             f"--window-size={w},{h}", f"--screenshot={shot}",
             f"file://{page}"],
            check=True, capture_output=True, timeout=120)
        return Image.open(shot).convert("RGB").copy()


def bloom(img: Image.Image) -> Image.Image:
    """Screen a blurred copy of the bright areas back over the frame."""
    arr = np.asarray(img).astype(np.float32)
    bright = np.clip(arr - BLOOM_THRESHOLD, 0, None) * \
        (255.0 / max(255 - BLOOM_THRESHOLD, 1))
    glow = Image.fromarray(bright.astype(np.uint8)).filter(
        ImageFilter.GaussianBlur(BLOOM_RADIUS * SCALE / 2))
    g = np.asarray(glow).astype(np.float32) * BLOOM_STRENGTH
    # screen blend keeps highlights from clipping to flat white
    out = 255.0 - (255.0 - arr) * (255.0 - g) / 255.0
    return Image.fromarray(np.clip(out, 0, 255).astype(np.uint8))


def rgb_split(img: Image.Image, shift: int = 1) -> Image.Image:
    """Sub-pixel red/blue displacement, mixed rather than replaced so glyph
    edges pick up a fringe without the whole stroke turning colour."""
    arr = np.asarray(img).astype(np.float32)
    out = arr.copy()
    m = RGB_SPLIT_MIX
    out[:, shift:, 0] = arr[:, shift:, 0] * (1 - m) + arr[:, :-shift, 0] * m
    out[:, :-shift, 2] = arr[:, :-shift, 2] * (1 - m) + arr[:, shift:, 2] * m
    return Image.fromarray(np.clip(out, 0, 255).astype(np.uint8))


def scanlines(img: Image.Image) -> Image.Image:
    # One dark CSS row per light one: the period has to be >= 2 CSS px or the
    # browser's downscale to width=880 averages the lines away entirely.
    arr = np.asarray(img).astype(np.float32)
    period = SCANLINE_PERIOD * SCALE
    mask = np.ones(arr.shape[0], dtype=np.float32)
    for row in range(SCALE):
        mask[row::period] = 1.0 - SCANLINE_DEPTH
    arr *= mask[:, None, None]
    return Image.fromarray(np.clip(arr, 0, 255).astype(np.uint8))


def grain(img: Image.Image, seed: int) -> Image.Image:
    rng = np.random.default_rng(seed)
    arr = np.asarray(img).astype(np.float32)
    noise = rng.normal(0.0, GRAIN_SIGMA, arr.shape[:2])[:, :, None]
    return Image.fromarray(np.clip(arr + noise, 0, 255).astype(np.uint8))


def _bayer(n: int = 8) -> np.ndarray:
    m = np.array([[0]], dtype=np.float32)
    while m.shape[0] < n:
        m = np.block([[4 * m, 4 * m + 2], [4 * m + 3, 4 * m + 1]])
    return m / m.size - 0.5


def quantise(img: Image.Image) -> Image.Image:
    """Ordered-dither to PALETTE. This is what makes the tones read as dots."""
    arr = np.asarray(img).astype(np.float32)
    tile = _bayer(8) * DITHER_STRENGTH
    reps = (arr.shape[0] // 8 + 1, arr.shape[1] // 8 + 1)
    offset = np.tile(tile, reps)[:arr.shape[0], :arr.shape[1], None]
    arr = np.clip(arr + offset, 0, 255)

    pal = np.array(PALETTE, dtype=np.float32)
    flat = arr.reshape(-1, 3)
    # nearest palette entry, in chunks so a big card does not blow up memory
    out = np.empty(flat.shape, dtype=np.uint8)
    for i in range(0, flat.shape[0], 200_000):
        block = flat[i:i + 200_000]
        idx = np.argmin(((block[:, None, :] - pal[None]) ** 2).sum(-1), axis=1)
        out[i:i + 200_000] = pal[idx].astype(np.uint8)
    return Image.fromarray(out.reshape(arr.shape))


def process(svg_path: str, png_path: str) -> None:
    w, h = svg_size(svg_path)
    img = rasterise(svg_path, w, h)
    if img.size != (w * SCALE, h * SCALE):
        img = img.resize((w * SCALE, h * SCALE), Image.LANCZOS)
    img = bloom(img)
    img = rgb_split(img)
    img = scanlines(img)
    # crc32, not hash(): str hashing is salted per process, so hash()
    # would reseed the grain on every run and churn the diff.
    img = grain(img, seed=zlib.crc32(
        os.path.basename(svg_path).encode()))
    img = quantise(img)
    img.convert("P", palette=Image.ADAPTIVE, colors=len(PALETTE)).save(
        png_path, optimize=True)
    size_kb = os.path.getsize(png_path) / 1024
    print(f"wrote {png_path} ({w * SCALE}x{h * SCALE}, {size_kb:.0f} KB)")


def main() -> None:
    wanted = sys.argv[1:]
    names = sorted(f[:-4] for f in os.listdir(PROFILE) if f.endswith(".svg"))
    if wanted:
        names = [n for n in names if n in wanted]
    if not names:
        raise SystemExit("no matching SVGs in profile/")
    for name in names:
        process(os.path.join(PROFILE, f"{name}.svg"),
                os.path.join(PROFILE, f"{name}.png"))


if __name__ == "__main__":
    main()
